-- Curated starter exercise catalog for local verification and AI planning.
INSERT INTO exercises (
  id,
  name,
  normalized_name,
  aliases,
  primary_muscles,
  secondary_muscles,
  equipment,
  movement_patterns,
  difficulty,
  instructions,
  safety_notes,
  source,
  validation_status,
  status,
  user_id,
  dedupe_key
) VALUES
(
  'b1000001-0000-4000-8000-000000000001',
  'Barbell Bench Press',
  'barbell bench press',
  '["bench press"]',
  '["chest"]',
  '["triceps","shoulders"]',
  '["barbell","bench"]',
  '["push"]',
  'intermediate',
  '["Lie on a flat bench with feet planted.","Grip the bar slightly wider than shoulder width.","Lower the bar to mid-chest with control.","Press up without bouncing the bar."]',
  '["Use a spotter or safety arms when lifting heavy.","Keep wrists stacked over elbows."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'barbell bench press::barbell|bench::chest'
),
(
  'b1000001-0000-4000-8000-000000000002',
  'Dumbbell Bench Press',
  'dumbbell bench press',
  '[]',
  '["chest"]',
  '["triceps","shoulders"]',
  '["dumbbell","bench"]',
  '["push"]',
  'beginner',
  '["Sit on a bench with dumbbells on thighs.","Lie back and position dumbbells over chest.","Lower with control until upper arms are parallel.","Press up while keeping shoulder blades retracted."]',
  '["Choose a weight you can control on the descent."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'dumbbell bench press::bench|dumbbell::chest'
),
(
  'b1000001-0000-4000-8000-000000000003',
  'Push-Up',
  'push up',
  '["push up"]',
  '["chest","triceps"]',
  '["shoulders","core"]',
  '["bodyweight"]',
  '["push"]',
  'beginner',
  '["Start in a high plank with hands under shoulders.","Lower chest toward the floor while keeping body straight.","Press back up without sagging hips."]',
  '["Modify on knees or an incline if needed."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'push up::bodyweight::chest|triceps'
),
(
  'b1000001-0000-4000-8000-000000000004',
  'Incline Dumbbell Press',
  'incline dumbbell press',
  '[]',
  '["chest"]',
  '["shoulders","triceps"]',
  '["dumbbell","bench"]',
  '["push"]',
  'intermediate',
  '["Set bench to 30-45 degrees.","Press dumbbells up over upper chest.","Lower with control to shoulder level."]',
  '["Avoid excessive arching of the lower back."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'incline dumbbell press::bench|dumbbell::chest'
),
(
  'b1000001-0000-4000-8000-000000000005',
  'Dumbbell Fly',
  'dumbbell fly',
  '["chest fly"]',
  '["chest"]',
  '["shoulders"]',
  '["dumbbell","bench"]',
  '["isolation"]',
  'intermediate',
  '["Lie on a bench with dumbbells over chest.","Open arms in a wide arc with soft elbows.","Squeeze chest to return dumbbells together."]',
  '["Use moderate weight to protect shoulders."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'dumbbell fly::bench|dumbbell::chest'
),
(
  'b1000001-0000-4000-8000-000000000006',
  'Barbell Row',
  'barbell row',
  '["bent-over row"]',
  '["back","lats"]',
  '["biceps","traps"]',
  '["barbell"]',
  '["pull"]',
  'intermediate',
  '["Hinge at hips with flat back.","Pull bar toward lower ribs.","Lower with control without rounding spine."]',
  '["Brace core and avoid jerking the weight."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'barbell row::barbell::back|lats'
),
(
  'b1000001-0000-4000-8000-000000000007',
  'Pull-Up',
  'pull up',
  '["pull up"]',
  '["back","lats"]',
  '["biceps"]',
  '["pull_up_bar","bodyweight"]',
  '["pull"]',
  'intermediate',
  '["Hang from bar with shoulder-width grip.","Pull chest toward bar by driving elbows down.","Lower under control to full hang."]',
  '["Use assistance bands if full reps are not yet available."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'pull up::bodyweight|pull_up_bar::back|lats'
),
(
  'b1000001-0000-4000-8000-000000000008',
  'Lat Pulldown',
  'lat pulldown',
  '[]',
  '["lats"]',
  '["back","biceps"]',
  '["cable","machine"]',
  '["pull"]',
  'beginner',
  '["Grip bar wider than shoulders.","Pull bar to upper chest while leaning slightly back.","Return with control without shrugging."]',
  '["Avoid pulling behind the neck."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'lat pulldown::cable|machine::lats'
),
(
  'b1000001-0000-4000-8000-000000000009',
  'Seated Cable Row',
  'seated cable row',
  '[]',
  '["back"]',
  '["lats","biceps"]',
  '["cable","machine"]',
  '["pull"]',
  'beginner',
  '["Sit tall with feet braced.","Pull handle toward lower ribs.","Extend arms forward without rounding upper back."]',
  '["Keep torso stable throughout the set."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'seated cable row::cable|machine::back'
),
(
  'b1000001-0000-4000-8000-000000000010',
  'Dumbbell Row',
  'dumbbell row',
  '["single-arm row"]',
  '["back","lats"]',
  '["biceps"]',
  '["dumbbell","bench"]',
  '["pull"]',
  'beginner',
  '["Place one knee and hand on bench.","Row dumbbell toward hip.","Lower slowly without twisting torso."]',
  '["Keep neck neutral."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'dumbbell row::bench|dumbbell::back|lats'
),
(
  'b1000001-0000-4000-8000-000000000011',
  'Face Pull',
  'face pull',
  '[]',
  '["shoulders","traps"]',
  '["back"]',
  '["cable","resistance_band"]',
  '["pull","isolation"]',
  'beginner',
  '["Set cable at face height with rope attachment.","Pull toward face with elbows high.","Externally rotate at end range."]',
  '["Use light load and focus on control."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'face pull::cable|resistance_band::shoulders|traps'
),
(
  'b1000001-0000-4000-8000-000000000012',
  'Overhead Press',
  'overhead press',
  '["military press"]',
  '["shoulders"]',
  '["triceps","core"]',
  '["barbell"]',
  '["push"]',
  'intermediate',
  '["Stand with bar at upper chest.","Press bar overhead without excessive lean.","Lower to chin or collarbone with control."]',
  '["Brace core and avoid arching excessively."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'overhead press::barbell::shoulders'
),
(
  'b1000001-0000-4000-8000-000000000013',
  'Dumbbell Shoulder Press',
  'dumbbell shoulder press',
  '[]',
  '["shoulders"]',
  '["triceps"]',
  '["dumbbell"]',
  '["push"]',
  'beginner',
  '["Start with dumbbells at shoulder height.","Press overhead until arms are extended.","Lower to ear level with control."]',
  '["Do not flare elbows excessively."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'dumbbell shoulder press::dumbbell::shoulders'
),
(
  'b1000001-0000-4000-8000-000000000014',
  'Lateral Raise',
  'lateral raise',
  '[]',
  '["shoulders"]',
  '[]',
  '["dumbbell"]',
  '["isolation"]',
  'beginner',
  '["Stand with dumbbells at sides.","Raise arms to shoulder height with soft elbows.","Lower slowly without swinging."]',
  '["Use lighter weight for strict form."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'lateral raise::dumbbell::shoulders'
),
(
  'b1000001-0000-4000-8000-000000000015',
  'Barbell Back Squat',
  'barbell back squat',
  '["back squat"]',
  '["quads","glutes"]',
  '["core","hamstrings"]',
  '["barbell"]',
  '["squat"]',
  'intermediate',
  '["Set bar on upper back and brace core.","Sit hips back and down to comfortable depth.","Drive through mid-foot to stand."]',
  '["Use safety pins or a spotter when needed."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'barbell back squat::barbell::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000016',
  'Goblet Squat',
  'goblet squat',
  '[]',
  '["quads","glutes"]',
  '["core"]',
  '["kettlebell","dumbbell"]',
  '["squat"]',
  'beginner',
  '["Hold weight at chest.","Squat between hips with upright torso.","Stand by driving through full foot."]',
  '["Keep heels down and knees tracking over toes."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'goblet squat::dumbbell|kettlebell::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000017',
  'Romanian Deadlift',
  'romanian deadlift',
  '["RDL"]',
  '["hamstrings","glutes"]',
  '["back"]',
  '["barbell","dumbbell"]',
  '["hinge"]',
  'intermediate',
  '["Hold weight at hip height with soft knees.","Hinge hips back while keeping bar close to legs.","Return by driving hips forward."]',
  '["Stop when hamstrings limit range without rounding back."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'romanian deadlift::barbell|dumbbell::glutes|hamstrings'
),
(
  'b1000001-0000-4000-8000-000000000018',
  'Conventional Deadlift',
  'conventional deadlift',
  '["deadlift"]',
  '["back","hamstrings","glutes"]',
  '["traps","core"]',
  '["barbell"]',
  '["hinge"]',
  'advanced',
  '["Set bar over mid-foot with flat back.","Drive through floor while keeping bar close.","Stand tall without hyperextending."]',
  '["Use proper bracing and avoid rounded back lifting."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'conventional deadlift::barbell::back|glutes|hamstrings'
),
(
  'b1000001-0000-4000-8000-000000000019',
  'Leg Press',
  'leg press',
  '[]',
  '["quads","glutes"]',
  '["hamstrings"]',
  '["machine"]',
  '["squat"]',
  'beginner',
  '["Place feet shoulder-width on platform.","Lower sled with control to comfortable depth.","Press away without locking knees aggressively."]',
  '["Keep lower back in contact with pad."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'leg press::machine::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000020',
  'Walking Lunge',
  'walking lunge',
  '[]',
  '["quads","glutes"]',
  '["hamstrings","core"]',
  '["dumbbell","bodyweight"]',
  '["lunge"]',
  'beginner',
  '["Step forward into a long lunge.","Keep front knee over mid-foot.","Push through front heel to stand and alternate."]',
  '["Use support if balance is limited."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'walking lunge::bodyweight|dumbbell::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000021',
  'Bulgarian Split Squat',
  'bulgarian split squat',
  '[]',
  '["quads","glutes"]',
  '["hamstrings"]',
  '["dumbbell","bench"]',
  '["lunge"]',
  'intermediate',
  '["Place rear foot on bench behind you.","Lower until front thigh is near parallel.","Drive through front foot to stand."]',
  '["Start bodyweight before adding load."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'bulgarian split squat::bench|dumbbell::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000022',
  'Leg Curl',
  'leg curl',
  '["hamstring curl"]',
  '["hamstrings"]',
  '[]',
  '["machine"]',
  '["isolation"]',
  'beginner',
  '["Set pad on lower calves.","Curl heels toward glutes.","Lower with control."]',
  '["Avoid lifting hips off pad."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'leg curl::machine::hamstrings'
),
(
  'b1000001-0000-4000-8000-000000000023',
  'Leg Extension',
  'leg extension',
  '[]',
  '["quads"]',
  '[]',
  '["machine"]',
  '["isolation"]',
  'beginner',
  '["Align knee with machine pivot.","Extend legs without locking hard.","Lower slowly to start position."]',
  '["Use moderate load for knee comfort."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'leg extension::machine::quads'
),
(
  'b1000001-0000-4000-8000-000000000024',
  'Standing Calf Raise',
  'standing calf raise',
  '["calf raise"]',
  '["calves"]',
  '[]',
  '["machine","bodyweight"]',
  '["isolation"]',
  'beginner',
  '["Stand on balls of feet at edge of step.","Rise onto toes with full range.","Lower heels below step level with control."]',
  '["Hold support if balance is needed."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'standing calf raise::bodyweight|machine::calves'
),
(
  'b1000001-0000-4000-8000-000000000025',
  'Hip Thrust',
  'hip thrust',
  '[]',
  '["glutes"]',
  '["hamstrings","core"]',
  '["barbell","bench"]',
  '["hinge"]',
  'intermediate',
  '["Place upper back on bench with bar over hips.","Drive hips up until torso is parallel to floor.","Lower with control without hyperextending."]',
  '["Use a pad for bar comfort."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'hip thrust::barbell|bench::glutes'
),
(
  'b1000001-0000-4000-8000-000000000026',
  'Plank',
  'plank',
  '[]',
  '["core"]',
  '["shoulders"]',
  '["bodyweight"]',
  '["isolation"]',
  'beginner',
  '["Hold forearm or high plank with straight line head to heels.","Brace abs and glutes.","Breathe steadily while maintaining position."]',
  '["Stop if lower back sags."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'plank::bodyweight::core'
),
(
  'b1000001-0000-4000-8000-000000000027',
  'Hanging Leg Raise',
  'hanging leg raise',
  '[]',
  '["core"]',
  '["hip_flexors"]',
  '["pull_up_bar"]',
  '["isolation"]',
  'intermediate',
  '["Hang from bar with shoulders engaged.","Raise legs with control to hip height or higher.","Lower without swinging."]',
  '["Bend knees to reduce difficulty if needed."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'hanging leg raise::pull_up_bar::core'
),
(
  'b1000001-0000-4000-8000-000000000028',
  'Cable Crunch',
  'cable crunch',
  '[]',
  '["core"]',
  '[]',
  '["cable"]',
  '["isolation"]',
  'beginner',
  '["Kneel facing cable with rope behind head.","Crunch down by flexing spine.","Return with control."]',
  '["Move from mid-back flexion, not neck pulling."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'cable crunch::cable::core'
),
(
  'b1000001-0000-4000-8000-000000000029',
  'Barbell Curl',
  'barbell curl',
  '[]',
  '["biceps"]',
  '["forearms"]',
  '["barbell","ez_bar"]',
  '["isolation"]',
  'beginner',
  '["Stand with underhand grip on bar.","Curl bar toward shoulders without swinging.","Lower slowly to full extension."]',
  '["Keep elbows close to torso."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'barbell curl::barbell|ez_bar::biceps'
),
(
  'b1000001-0000-4000-8000-000000000030',
  'Dumbbell Curl',
  'dumbbell curl',
  '[]',
  '["biceps"]',
  '["forearms"]',
  '["dumbbell"]',
  '["isolation"]',
  'beginner',
  '["Stand with dumbbells at sides.","Curl one or both arms with control.","Lower to full extension."]',
  '["Avoid using momentum from hips."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'dumbbell curl::dumbbell::biceps'
),
(
  'b1000001-0000-4000-8000-000000000031',
  'Hammer Curl',
  'hammer curl',
  '[]',
  '["biceps","forearms"]',
  '[]',
  '["dumbbell"]',
  '["isolation"]',
  'beginner',
  '["Hold dumbbells neutral grip.","Curl while keeping palms facing each other.","Lower under control."]',
  '["Keep wrists neutral."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'hammer curl::dumbbell::biceps|forearms'
),
(
  'b1000001-0000-4000-8000-000000000032',
  'Triceps Pushdown',
  'triceps pushdown',
  '["cable pushdown"]',
  '["triceps"]',
  '[]',
  '["cable"]',
  '["isolation"]',
  'beginner',
  '["Stand at cable with elbows at sides.","Extend arms down fully.","Return with control without moving upper arm."]',
  '["Keep shoulders down and stable."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'triceps pushdown::cable::triceps'
),
(
  'b1000001-0000-4000-8000-000000000033',
  'Overhead Triceps Extension',
  'overhead triceps extension',
  '[]',
  '["triceps"]',
  '[]',
  '["dumbbell","cable"]',
  '["isolation"]',
  'beginner',
  '["Hold weight overhead with elbows forward.","Lower behind head by bending elbows.","Extend arms to start position."]',
  '["Use manageable load overhead."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'overhead triceps extension::cable|dumbbell::triceps'
),
(
  'b1000001-0000-4000-8000-000000000034',
  'Skull Crusher',
  'skull crusher',
  '["lying triceps extension"]',
  '["triceps"]',
  '[]',
  '["barbell","ez_bar","bench"]',
  '["isolation"]',
  'intermediate',
  '["Lie on bench with arms extended over chest.","Bend elbows to lower bar toward forehead.","Extend arms without flaring elbows wide."]',
  '["Use spotter or moderate load."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'skull crusher::barbell|bench|ez_bar::triceps'
),
(
  'b1000001-0000-4000-8000-000000000035',
  'Parallel Bar Dip',
  'parallel bar dip',
  '["dip"]',
  '["chest","triceps"]',
  '["shoulders"]',
  '["bodyweight"]',
  '["push"]',
  'intermediate',
  '["Support body on parallel bars.","Lower until upper arms are near parallel.","Press back up with control."]',
  '["Use assistance if shoulder discomfort appears."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'parallel bar dip::bodyweight::chest|triceps'
),
(
  'b1000001-0000-4000-8000-000000000036',
  'Kettlebell Swing',
  'kettlebell swing',
  '[]',
  '["glutes","hamstrings"]',
  '["core"]',
  '["kettlebell"]',
  '["hinge","cardio"]',
  'intermediate',
  '["Hinge to hike kettlebell back between legs.","Drive hips forward to swing to chest height.","Let bell float down and repeat rhythmically."]',
  '["Power comes from hips, not arms or lower back."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'kettlebell swing::kettlebell::glutes|hamstrings'
),
(
  'b1000001-0000-4000-8000-000000000037',
  'Farmer Carry',
  'farmer carry',
  '["farmers walk"]',
  '["core","forearms"]',
  '["shoulders","traps"]',
  '["dumbbell","kettlebell"]',
  '["carry"]',
  'beginner',
  '["Pick up heavy weights at sides.","Walk tall with shoulders packed.","Maintain steady pace for prescribed distance or time."]',
  '["Keep path clear and grip secure."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'farmer carry::dumbbell|kettlebell::core|forearms'
),
(
  'b1000001-0000-4000-8000-000000000038',
  'Bicycle Crunch',
  'bicycle crunch',
  '[]',
  '["core"]',
  '["hip_flexors"]',
  '["bodyweight"]',
  '["rotation"]',
  'beginner',
  '["Lie on back with hands behind head.","Bring opposite elbow toward knee while extending other leg.","Alternate sides with controlled tempo."]',
  '["Avoid pulling on neck."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'bicycle crunch::bodyweight::core'
),
(
  'b1000001-0000-4000-8000-000000000039',
  'Mountain Climber',
  'mountain climber',
  '[]',
  '["core","hip_flexors"]',
  '["shoulders"]',
  '["bodyweight"]',
  '["cardio"]',
  'beginner',
  '["Start in high plank.","Drive knees toward chest alternately.","Keep hips low and core braced."]',
  '["Slow down if form breaks down."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'mountain climber::bodyweight::core|hip_flexors'
),
(
  'b1000001-0000-4000-8000-000000000040',
  'Burpee',
  'burpee',
  '[]',
  '["quads","chest","core"]',
  '["shoulders"]',
  '["bodyweight"]',
  '["cardio"]',
  'intermediate',
  '["Drop to hands and jump feet back to plank.","Perform push-up optional.","Jump feet in and stand with small jump."]',
  '["Step back instead of jumping if needed."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'burpee::bodyweight::chest|core|quads'
),
(
  'b1000001-0000-4000-8000-000000000041',
  'Rowing Machine',
  'rowing machine',
  '["rower"]',
  '["back","quads"]',
  '["core","biceps"]',
  '["machine"]',
  '["cardio","pull"]',
  'beginner',
  '["Drive with legs first then lean back slightly.","Pull handle to lower ribs.","Return in reverse order with control."]',
  '["Maintain smooth stroke rate."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'rowing machine::machine::back|quads'
),
(
  'b1000001-0000-4000-8000-000000000042',
  'Treadmill Run',
  'treadmill run',
  '["running"]',
  '["quads","calves"]',
  '["hamstrings","core"]',
  '["machine"]',
  '["cardio"]',
  'beginner',
  '["Warm up at easy pace.","Maintain upright posture and relaxed shoulders.","Cool down gradually."]',
  '["Use safety clip and appropriate speed."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'treadmill run::machine::calves|quads'
),
(
  'b1000001-0000-4000-8000-000000000043',
  'Band Pull-Apart',
  'band pull apart',
  '["resistance band pull apart"]',
  '["shoulders","back"]',
  '["traps"]',
  '["resistance_band"]',
  '["pull","isolation"]',
  'beginner',
  '["Hold band at chest height with arms extended.","Pull band apart by squeezing shoulder blades.","Return with control."]',
  '["Use light band tension for warm-up quality reps."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'band pull apart::resistance_band::back|shoulders'
),
(
  'b1000001-0000-4000-8000-000000000044',
  'Glute Bridge',
  'glute bridge',
  '[]',
  '["glutes"]',
  '["hamstrings","core"]',
  '["bodyweight"]',
  '["hinge"]',
  'beginner',
  '["Lie on back with knees bent and feet flat.","Drive hips up by squeezing glutes.","Lower without losing tension at bottom."]',
  '["Avoid overarching lower back at top."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'glute bridge::bodyweight::glutes'
),
(
  'b1000001-0000-4000-8000-000000000045',
  'Step-Up',
  'step up',
  '[]',
  '["quads","glutes"]',
  '["hamstrings"]',
  '["dumbbell","bench"]',
  '["lunge"]',
  'beginner',
  '["Place one foot fully on box or bench.","Drive through front heel to stand on box.","Lower with control and repeat."]',
  '["Choose box height that allows stable knee alignment."]',
  'system_seed',
  'validated',
  'active',
  NULL,
  'step up::bench|dumbbell::glutes|quads'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO exercises (
  id,
  name,
  normalized_name,
  aliases,
  primary_muscles,
  secondary_muscles,
  equipment,
  movement_patterns,
  modalities,
  difficulty,
  instructions,
  safety_notes,
  media,
  source,
  validation_status,
  status,
  user_id,
  dedupe_key
) VALUES
(
  'b1000001-0000-4000-8000-000000000046',
  'Downward Dog',
  'downward dog',
  '["adho mukha svanasana"]',
  '["shoulders","hamstrings","calves"]',
  '["core"]',
  '["bodyweight","yoga_mat"]',
  '["mobility","flexibility"]',
  '["yoga","mobility"]',
  'beginner',
  '["Start on hands and knees.","Lift hips up and back to form an inverted V.","Press heels toward floor while lengthening spine."]',
  '["Bend knees if hamstrings feel tight.","Avoid this pose if you have wrist discomfort."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'downward dog::bodyweight|yoga_mat::calves|hamstrings|shoulders'
),
(
  'b1000001-0000-4000-8000-000000000047',
  'Warrior II',
  'warrior ii',
  '["virabhadrasana ii"]',
  '["quads","glutes"]',
  '["core","shoulders"]',
  '["bodyweight","yoga_mat"]',
  '["lunge","balance"]',
  '["yoga","mobility"]',
  'beginner',
  '["Step one foot back into a wide stance.","Bend front knee over ankle and extend arms parallel to floor.","Hold steady gaze over front hand."]',
  '["Keep front knee tracking over toes.","Reduce depth if balance is unstable."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'warrior ii::bodyweight|yoga_mat::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000048',
  'Cat-Cow',
  'cat cow',
  '["cat cow stretch"]',
  '["core","back"]',
  '["shoulders"]',
  '["bodyweight","yoga_mat"]',
  '["mobility","flexibility"]',
  '["mobility","wellness"]',
  'beginner',
  '["Start on hands and knees with neutral spine.","Inhale and arch back while lifting chest (cow).","Exhale and round spine while tucking chin (cat)."]',
  '["Move slowly and stay within comfortable range."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'cat cow::bodyweight|yoga_mat::back|core'
),
(
  'b1000001-0000-4000-8000-000000000049',
  'World''s Greatest Stretch',
  'world greatest stretch',
  '["worlds greatest stretch"]',
  '["hip_flexors","glutes"]',
  '["hamstrings","core"]',
  '["bodyweight"]',
  '["lunge","mobility"]',
  '["mobility","athletic_performance"]',
  'intermediate',
  '["Step into a deep lunge with back knee down.","Place inside hand on floor and rotate open with other arm.","Hold briefly then switch sides."]',
  '["Use padding under back knee if needed.","Stop if sharp hip or knee discomfort appears."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'world greatest stretch::bodyweight::glutes|hip_flexors'
),
(
  'b1000001-0000-4000-8000-000000000050',
  '90/90 Hip Switch',
  '90 90 hip switch',
  '["90-90 hip switch"]',
  '["glutes","hip_flexors"]',
  '["core"]',
  '["bodyweight","yoga_mat"]',
  '["mobility","rotation"]',
  '["mobility"]',
  'beginner',
  '["Sit with front and back legs at roughly 90 degrees.","Rotate hips to switch sides with control.","Keep torso tall throughout."]',
  '["Use hands on floor for support if needed.","Avoid forcing range of motion."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  '90 90 hip switch::bodyweight|yoga_mat::glutes|hip_flexors'
),
(
  'b1000001-0000-4000-8000-000000000051',
  'Box Jump',
  'box jump',
  '[]',
  '["quads","glutes","calves"]',
  '["core"]',
  '["box","bodyweight"]',
  '["plyometric","squat"]',
  '["plyometrics","athletic_performance"]',
  'intermediate',
  '["Stand arm''s length from box with feet hip-width.","Swing arms and jump onto box landing softly.","Step down under control and reset."]',
  '["Choose a box height you can land on safely.","Step down instead of jumping down if needed."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'box jump::bodyweight|box::calves|glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000052',
  'Broad Jump',
  'broad jump',
  '["standing long jump"]',
  '["quads","glutes","calves"]',
  '["core"]',
  '["bodyweight"]',
  '["plyometric","squat"]',
  '["plyometrics","athletic_performance"]',
  'intermediate',
  '["Swing arms back then forward while loading hips.","Jump forward for distance with soft landing.","Reset fully between reps."]',
  '["Land with knees tracking over toes.","Reduce jump distance if landing feels unstable."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'broad jump::bodyweight::calves|glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000053',
  'Depth Jump',
  'depth jump',
  '[]',
  '["quads","glutes","calves"]',
  '["core"]',
  '["box","bodyweight"]',
  '["plyometric","squat"]',
  '["plyometrics","athletic_performance"]',
  'advanced',
  '["Step off low box and land softly on both feet.","Immediately jump vertically or horizontally.","Focus on quick ground contact."]',
  '["Use low box height only.","Skip if you feel knee or ankle discomfort."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'depth jump::bodyweight|box::calves|glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000054',
  'Skater Hop',
  'skater hop',
  '["lateral bound"]',
  '["glutes","quads"]',
  '["calves","core"]',
  '["bodyweight"]',
  '["plyometric","lunge"]',
  '["plyometrics","athletic_performance"]',
  'intermediate',
  '["Jump laterally from one leg to the other.","Land softly and pause briefly for balance.","Use arms for counterbalance."]',
  '["Reduce jump distance if balance is lost.","Stop if ankle or knee discomfort increases."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'skater hop::bodyweight::glutes|quads'
),
(
  'b1000001-0000-4000-8000-000000000055',
  'Medicine Ball Slam',
  'medicine ball slam',
  '[]',
  '["core","shoulders"]',
  '["lats","traps"]',
  '["medicine_ball"]',
  '["rotation","plyometric"]',
  '["athletic_performance","conditioning"]',
  'intermediate',
  '["Lift medicine ball overhead with extended hips.","Slam ball down in front while bracing core.","Pick up and repeat with controlled breathing."]',
  '["Use a non-bounce slam ball on a safe surface.","Avoid overhead slam if shoulder discomfort is present."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'medicine ball slam::medicine_ball::core|shoulders'
),
(
  'b1000001-0000-4000-8000-000000000056',
  'Agility Ladder Drill',
  'agility ladder drill',
  '["ladder drill"]',
  '["calves","quads"]',
  '["core","hip_flexors"]',
  '["bodyweight"]',
  '["plyometric","cardio"]',
  '["athletic_performance","conditioning"]',
  'intermediate',
  '["Place one foot in each ladder square with quick steps.","Stay on balls of feet with upright posture.","Maintain rhythm for the prescribed duration."]',
  '["Start slow before increasing speed.","Stop if foot catches in ladder rungs."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'agility ladder drill::bodyweight::calves|quads'
),
(
  'b1000001-0000-4000-8000-000000000057',
  'Diaphragmatic Breathing',
  'diaphragmatic breathing',
  '["belly breathing"]',
  '["core"]',
  '[]',
  '["bodyweight","yoga_mat"]',
  '["mobility"]',
  '["wellness","mobility"]',
  'beginner',
  '["Lie or sit comfortably with one hand on belly.","Inhale through nose and expand belly.","Exhale slowly through mouth and relax shoulders."]',
  '["Keep breathing smooth and unforced.","Stop if lightheadedness occurs."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'diaphragmatic breathing::bodyweight|yoga_mat::core'
),
(
  'b1000001-0000-4000-8000-000000000058',
  'Gentle Neck Mobility',
  'gentle neck mobility',
  '["neck circles"]',
  '["traps"]',
  '[]',
  '["bodyweight"]',
  '["mobility","flexibility"]',
  '["wellness","mobility"]',
  'beginner',
  '["Sit tall with shoulders relaxed.","Slowly turn head left and right within comfortable range.","Optional: gentle side bends without forcing stretch."]',
  '["Avoid rapid or forced neck movements.","Stop if numbness, tingling, or sharp discomfort appears."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'gentle neck mobility::bodyweight::traps'
),
(
  'b1000001-0000-4000-8000-000000000059',
  'Child''s Pose',
  'child pose',
  '["balasana"]',
  '["back"]',
  '["shoulders","hip_flexors"]',
  '["bodyweight","yoga_mat"]',
  '["mobility","flexibility"]',
  '["yoga","wellness"]',
  'beginner',
  '["Kneel and sit hips back toward heels.","Reach arms forward and rest forehead toward floor.","Breathe slowly and relax shoulders."]',
  '["Place cushion under knees if needed.","Skip deep knee flexion if uncomfortable."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'child pose::bodyweight|yoga_mat::back'
),
(
  'b1000001-0000-4000-8000-000000000060',
  'Foam Roll Quads',
  'foam roll quads',
  '["quad foam rolling"]',
  '["quads"]',
  '[]',
  '["foam_roller","bodyweight"]',
  '["mobility"]',
  '["mobility","wellness"]',
  'beginner',
  '["Lie face down with foam roller under thighs.","Roll slowly from hip to knee pausing on tender spots.","Keep core lightly engaged."]',
  '["Avoid rolling directly on knee joint.","Reduce pressure if discomfort is sharp."]',
  '{"refs":[],"fallbackLabel":"Demonstration coming soon"}',
  'system_seed',
  'validated',
  'active',
  NULL,
  'foam roll quads::bodyweight|foam_roller::quads'
)
ON CONFLICT (id) DO NOTHING;

-- Idempotent taxonomy/media defaults for legacy seed rows missing explicit columns.
UPDATE exercises
SET modalities = '["conditioning"]'::jsonb
WHERE source = 'system_seed'
  AND movement_patterns @> '["cardio"]'::jsonb
  AND modalities = '["strength"]'::jsonb;

UPDATE exercises
SET modalities = '["mobility","wellness"]'::jsonb
WHERE source = 'system_seed'
  AND normalized_name IN ('cat cow', 'world greatest stretch', '90 90 hip switch', 'foam roll quads');

UPDATE exercises
SET modalities = '["yoga","mobility"]'::jsonb
WHERE source = 'system_seed'
  AND normalized_name IN ('downward dog', 'warrior ii', 'child pose');

UPDATE exercises
SET modalities = '["plyometrics","athletic_performance"]'::jsonb
WHERE source = 'system_seed'
  AND normalized_name IN ('box jump', 'broad jump', 'depth jump', 'skater hop');

UPDATE exercises
SET modalities = '["athletic_performance","conditioning"]'::jsonb
WHERE source = 'system_seed'
  AND normalized_name IN ('medicine ball slam', 'agility ladder drill');

UPDATE exercises
SET modalities = '["wellness","mobility"]'::jsonb
WHERE source = 'system_seed'
  AND normalized_name IN ('diaphragmatic breathing', 'gentle neck mobility');

UPDATE exercises
SET media = '{"refs":[],"fallbackLabel":"Demonstration coming soon"}'::jsonb
WHERE source = 'system_seed'
  AND media = '{"refs":[],"fallbackLabel":null}'::jsonb;
