-- Curated starter catalog for local verification. Macro values are estimates only.
INSERT INTO recipes (
  id,
  name,
  description,
  ingredients,
  preparation_steps,
  servings,
  estimated_calories,
  protein_grams,
  carbs_grams,
  fat_grams,
  fiber_grams,
  meal_types,
  tags,
  restriction_tags,
  allergen_tags,
  prep_minutes,
  cook_minutes,
  source,
  status
) VALUES
(
  'a1000001-0000-4000-8000-000000000001',
  'Greek yogurt berry bowl',
  'A quick breakfast with protein and fiber from berries and yogurt.',
  '[{"name":"Greek yogurt","quantity":1,"unit":"cup"},{"name":"Mixed berries","quantity":0.5,"unit":"cup"},{"name":"Chia seeds","quantity":1,"unit":"tbsp"}]',
  '["Add yogurt to a bowl.","Top with berries and chia seeds."]',
  1,
  320,
  24,
  36,
  8,
  6,
  '["breakfast"]',
  '["high_protein","quick"]',
  '["contains_dairy"]',
  '["dairy"]',
  5,
  0,
  'health_tracer_seed',
  'active'
),
(
  'a1000001-0000-4000-8000-000000000002',
  'Turkey and veggie wrap',
  'A balanced lunch wrap with lean protein and vegetables.',
  '[{"name":"Whole wheat tortilla","quantity":1,"unit":"each"},{"name":"Sliced turkey","quantity":4,"unit":"oz"},{"name":"Spinach","quantity":1,"unit":"cup"},{"name":"Hummus","quantity":2,"unit":"tbsp"}]',
  '["Spread hummus on the tortilla.","Layer turkey and spinach.","Roll tightly and slice."]',
  1,
  410,
  32,
  38,
  14,
  8,
  '["lunch"]',
  '["balanced","portable"]',
  '["contains_gluten"]',
  '["gluten"]',
  10,
  0,
  'health_tracer_seed',
  'active'
),
(
  'a1000001-0000-4000-8000-000000000003',
  'Salmon with roasted vegetables',
  'A dinner plate with omega-3 rich salmon and colorful vegetables.',
  '[{"name":"Salmon fillet","quantity":5,"unit":"oz"},{"name":"Broccoli florets","quantity":1,"unit":"cup"},{"name":"Olive oil","quantity":1,"unit":"tbsp"},{"name":"Lemon","quantity":0.5,"unit":"each"}]',
  '["Season salmon and vegetables.","Roast at 400F for 18 minutes.","Finish with lemon."]',
  1,
  520,
  38,
  22,
  28,
  7,
  '["dinner"]',
  '["high_protein","omega_3"]',
  '["contains_fish"]',
  '["fish"]',
  10,
  20,
  'health_tracer_seed',
  'active'
),
(
  'a1000001-0000-4000-8000-000000000004',
  'Apple with almond butter',
  'A simple snack pairing fruit with healthy fats.',
  '[{"name":"Apple","quantity":1,"unit":"medium"},{"name":"Almond butter","quantity":1,"unit":"tbsp"}]',
  '["Slice the apple.","Serve with almond butter for dipping."]',
  1,
  210,
  5,
  28,
  10,
  5,
  '["snack"]',
  '["quick","plant_based"]',
  '["contains_tree_nuts"]',
  '["tree_nuts"]',
  3,
  0,
  'health_tracer_seed',
  'active'
),
(
  'a1000001-0000-4000-8000-000000000005',
  'Tofu veggie stir fry',
  'A plant-based dinner with tofu and mixed vegetables over rice.',
  '[{"name":"Firm tofu","quantity":6,"unit":"oz"},{"name":"Mixed vegetables","quantity":2,"unit":"cups"},{"name":"Brown rice","quantity":0.75,"unit":"cup cooked"},{"name":"Soy sauce","quantity":1,"unit":"tbsp"}]',
  '["Cube and sear tofu.","Stir fry vegetables.","Combine with rice and soy sauce."]',
  1,
  480,
  28,
  54,
  16,
  9,
  '["dinner","lunch"]',
  '["plant_based","balanced"]',
  '["vegan","contains_soy"]',
  '["soy"]',
  15,
  15,
  'health_tracer_seed',
  'active'
)
ON CONFLICT (id) DO NOTHING;
