import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  body: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 24,
  },
  button: {
    alignSelf: "flex-start",
    backgroundColor: "#2563eb",
    borderRadius: 10,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonSecondary: {
    backgroundColor: "#e2e8f0",
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  buttonTextSecondary: {
    color: "#0f172a",
  },
  card: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  cardTitle: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
  centerContent: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  checkboxRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
  },
  chip: {
    backgroundColor: "#eff6ff",
    borderRadius: 999,
    color: "#1d4ed8",
    fontSize: 13,
    marginBottom: 6,
    marginRight: 6,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  choiceBody: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  choiceMeta: {
    color: "#64748b",
    fontSize: 12,
    marginTop: 4,
  },
  choiceRow: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  choiceRowDisabled: {
    opacity: 0.55,
  },
  choiceRowSelected: {
    borderColor: "#2563eb",
    backgroundColor: "#eff6ff",
  },
  choiceTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "600",
  },
  errorText: {
    color: "#b91c1c",
    fontSize: 14,
    marginTop: 8,
  },
  eyebrow: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 10,
    borderWidth: 1,
    color: "#0f172a",
    fontSize: 16,
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  label: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "600",
  },
  listItem: {
    color: "#334155",
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 4,
  },
  meta: {
    color: "#64748b",
    fontSize: 14,
    marginBottom: 4,
  },
  noticeBody: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  noticeCard: {
    backgroundColor: "#fffbeb",
    borderColor: "#fde68a",
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  noticeTitle: {
    color: "#92400e",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  primaryButton: {
    alignSelf: "flex-start",
    backgroundColor: "#2563eb",
    borderRadius: 10,
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  rowBetween: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  screen: {
    backgroundColor: "#f8fafc",
    flex: 1,
  },
  screenContent: {
    padding: 20,
    paddingBottom: 40,
  },
  screenScroll: {
    backgroundColor: "#f8fafc",
    flexGrow: 1,
    padding: 20,
    paddingBottom: 40,
  },
  secondaryButton: {
    alignSelf: "flex-start",
    backgroundColor: "#e2e8f0",
    borderRadius: 10,
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "600",
  },
  sectionLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  subtitle: {
    color: "#475569",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 16,
  },
  targetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  targetPill: {
    backgroundColor: "#f1f5f9",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  targetPillText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "600",
  },
  title: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 12,
  },
});
