/**
 * llm-emission/workout.ts — Workout-domain LLM emission schemas.
 *
 * EMISSION schemas describe what a domain LLM may EMIT on the OpenAI strict
 * structured-output wire — NOT what the backend accepts. The canonical
 * proposal payload schemas (workouts.ts) remain the source of truth; the
 * ProposalNormalizationService bridges emission → canonical (name-only
 * exercises → catalog exerciseId / pendingExerciseRef).
 *
 * Strict-mode compatibility BY CONSTRUCTION (see llm-emission/index.ts):
 *  - `.strict()` objects only (→ additionalProperties:false)
 *  - NO `.optional()` — every optional field is `.nullable()` instead; the
 *    provider strips explicit nulls (stripExplicitNulls) before the canonical
 *    Zod parse, so `null` becomes "absent" downstream.
 *  - no `.default()`, no transforms (plain z.number(), never llmInt),
 *    no refine/superRefine, no z.record.
 *  - no min/max bounds — canonical schemas own all bounds and the full
 *    ProposalValidationService stack re-validates after normalization.
 *
 * Intentionally OMITTED emission fields (server-owned — the LLM must not be
 * able to fight the server stamps):
 *  - estimatedSessionCalorieBurn / calorieEstimateProvenance /
 *    caloriePerHourRate — ActionResolver always scrubs these and re-stamps
 *    only from the trusted workout domain_answer calorie fields.
 *  - pendingExercises — generated by the workout exercise normalizer.
 *  - adaptationMetadata — auxiliary metadata never instructed by the prompts.
 *  - attachmentRefId — stamped from server turn state, never LLM-authored.
 *  - structured/legacy exercise union — emission is name-based ONLY; the
 *    normalizer is the bridge to the catalog-backed structured form.
 */

import { z } from "zod";
import { workoutWeekdaySchema } from "../workouts.js";
import {
  displayDerivedOpSchema,
  displayFieldKindSchema,
} from "../display-contract.js";

// ---------------------------------------------------------------------------
// Display contract emission (shared by workout plan + activity log payloads)
// ---------------------------------------------------------------------------

export const displayFieldLlmEmissionSchema = z
  .object({
    key: z.string(),
    label: z.string(),
    kind: displayFieldKindSchema,
    unit: z.string().nullable(),
    value: z.number().nullable(),
    textValue: z.string().nullable(),
    min: z.number().nullable(),
    max: z.number().nullable(),
    step: z.number().nullable(),
    editable: z.boolean(),
  })
  .strict();

export const displayDerivedLlmEmissionSchema = z
  .object({
    target: z.string(),
    label: z.string(),
    unit: z.string().nullable(),
    op: displayDerivedOpSchema,
    inputs: z.array(z.string()),
    isPrimaryTotal: z.boolean(),
  })
  .strict();

export const displayContractLlmEmissionSchema = z
  .object({
    version: z.literal(1),
    title: z.string().nullable(),
    fields: z.array(displayFieldLlmEmissionSchema),
    derived: z.array(displayDerivedLlmEmissionSchema),
  })
  .strict();

// ---------------------------------------------------------------------------
// create_workout_plan / adapt_workout_plan
// ---------------------------------------------------------------------------

/** Name-based exercise — matches the canonical legacy workoutExerciseSchema fields. */
export const workoutExerciseLlmEmissionSchema = z
  .object({
    name: z.string(),
    target: z.string().nullable(),
    sets: z.number().nullable(),
    /** Canonical reps accepts string or number (number is normalized to string). */
    reps: z.union([z.string(), z.number()]).nullable(),
    notes: z.string().nullable(),
  })
  .strict();

export const workoutPlanDayLlmEmissionSchema = z
  .object({
    weekday: workoutWeekdaySchema,
    focus: z.string(),
    exercises: z.array(workoutExerciseLlmEmissionSchema),
  })
  .strict();

export const workoutPlanLlmEmissionSchema = z
  .object({
    title: z.string(),
    summary: z.string(),
    days: z.array(workoutPlanDayLlmEmissionSchema),
    notes: z.array(z.string()),
    displayContract: displayContractLlmEmissionSchema.nullable(),
  })
  .strict();

// ---------------------------------------------------------------------------
// adapt_workout_plan_from_progress — wrapper with a nested plan.
// recoverySourceRefs is omitted: recovery-context refs are server-derived.
// ---------------------------------------------------------------------------

export const adaptWorkoutPlanFromProgressLlmEmissionSchema = z
  .object({
    plan: workoutPlanLlmEmissionSchema,
    sourceSummaryId: z.string().nullable(),
    sourceTrendObservationIds: z.array(z.string()),
    allowVolumeIncrease: z.boolean().nullable(),
  })
  .strict();

// ---------------------------------------------------------------------------
// log_workout_activity
//
// estimatedCalories / ratePerHour stay emittable to match the prompt example,
// but ActionResolver scrubs both and re-stamps from the trusted domain_answer
// calorie fields — the payload values are advisory generation guidance only.
// ---------------------------------------------------------------------------

export const logWorkoutActivityLlmEmissionSchema = z
  .object({
    activityType: z.string(),
    title: z.string(),
    durationMinutes: z.number(),
    intensity: z.enum(["light", "moderate", "vigorous"]).nullable(),
    performedAt: z.string(),
    estimatedCalories: z.number().nullable(),
    ratePerHour: z.number().nullable(),
    displayContract: displayContractLlmEmissionSchema.nullable(),
  })
  .strict();
