import type { DeterministicProposalTriggersConfig } from "./ai-behavior-config.js";

export const DEFAULT_LOW_MOOD_STRESS_FATIGUE_PHRASES = [
  "feel bad",
  "feeling bad",
  "feel awful",
  "feeling awful",
  "feel terrible",
  "feeling terrible",
  "feel low",
  "feeling low",
  "feel down",
  "feeling down",
  "feel rough",
  "feeling rough",
  "not doing well",
  "having a bad day",
  "stressed",
  "stressful",
  "overwhelmed",
  "burnt out",
  "burned out",
  "tired",
  "exhausted",
  "fatigue",
  "fatigued",
  "no energy",
  "low energy",
] as const;

export const DEFAULT_NUTRITION_INCIDENT_PHRASES = [
  "cheat meal",
  "cheat day",
  "ate too much",
  "overate",
  "forgot to log",
  "missed log",
  "didn't log",
  "did not log",
  "i ate this",
  "ate this",
  "had this for",
  "food photo",
  "picture of my meal",
  "photo of my meal",
  "off plan meal",
  "went off plan",
] as const;

export const DEFAULT_RECIPE_RECOMMENDATION_PHRASES = [
  "meal idea",
  "meal ideas",
  "recipe idea",
  "recipe ideas",
  "what should i eat",
  "dinner idea",
  "lunch idea",
  "breakfast idea",
  "suggest a recipe",
  "recommend a recipe",
  "food ideas",
  "ideas for dinner",
  "ideas for lunch",
  "ideas for breakfast",
  "what can i cook",
  "what to cook",
] as const;

export const DEFAULT_DETERMINISTIC_PROPOSAL_TRIGGERS: DeterministicProposalTriggersConfig = {
  maxMergedProposals: 5,
  wellbeingCheckin: {
    enabled: true,
    moodPhrases: [...DEFAULT_LOW_MOOD_STRESS_FATIGUE_PHRASES],
    excludeContainsPhrases: ["hungry", "not losing weight"],
    excludeWhenNutritionIncidentSignal: true,
    requireNoTodayCheckIn: true,
    skipWhenCrisis: true,
  },
  nutritionIncident: {
    enabled: true,
    phrases: [...DEFAULT_NUTRITION_INCIDENT_PHRASES],
    skipWhenCrisis: true,
  },
  recipeRecommendation: {
    enabled: true,
    phrases: [...DEFAULT_RECIPE_RECOMMENDATION_PHRASES],
    excludeWhenNutritionIncidentSignal: true,
    skipWhenCrisis: true,
  },
};
